services:
  ui:
    image: nguyenc123/daddy_ui
    ports:
      - "80:80"
  daddy:
    image: nguyenc123/daddy_server
    ports:
      - "8000:8000"
    environment:
      DB_URL: "mongodb://cuongnguyen:abcxyz@mongodb"
      DB_NAME: "daddy"
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cuongnguyen
      - MONGO_INITDB_ROOT_PASSWORD=abcxyz
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
    driver: local 